embedding_size: 64
feat_embed_dim: 64

n_mm_layers: 1
n_layers: 2
mm_image_weight: 0.1
learning_rate: [0.0001]
reg_weight: [0.001]


dropout: [0.5]

# Baby
cl_weight: [0.005]
epsilon: [5]
lambda1: [0.001]
pvn_weight: [0.01]
knn_k: 10

# Sports
#cl_weight: [0.01]
#epsilon: [2]
#lambda1: [0.05]
#pvn_weight: [0.01]
#knn_k: 10

# Clothing
#cl_weight: [0.01]
#epsilon: [0.2]
#lambda1: [0.01]
#pvn_weight: [0.005]
#knn_k: 5

hyper_parameters: ["reg_weight", "learning_rate", 'dropout', 'cl_weight', 'epsilon', 'lambda1', 'pvn_weight']